<h1>Robinzhao Image Optimiser</h1>

<h2>Description</h2>

<p>This plugin is intended to optimize JPG images that uploaded via Media Uploader.</p>

<p>It reduces the image size / resolution for web pages. </p>

<p>The Tool behind this plugin is <a href="https://www.imagemagick.org/script/index.php" target="_blank">Imagemagick</a>. and <a href="http://wp-cli.org/" target="_blank">WPCLI</a></p>

<h3>What this plugin will apply to JPG files:</h3>
<p style="background-color:#fff">mogrify -strip -interlace Plane -quality 85% -resize '768x432>' -sampling-factor 4:2:0 <?= ABSPATH; ?>wp-content/uploads/2017/05/example.jpg</p>
<p>To understand what above command will do, check Imagemagick official site.</p>

<h3>Cronjob</h3>
<p>In order to monitor and convert all your future images, you need to setup a cronjob on your server.</p>
<p>Here we have a console script with <a href="http://wp-cli.org/" target="_blank">WPCLI</a> you can set up on your server.</p>

<p style="background-color:#fff">*/30 * * * * wp io run --path=<?= ABSPATH;?></p>


<p class="warn">This plugin will modify the images directly so
    <span style="font-weight: bold">use at your own risk</span>.
</p>
